### ISSUE TITLE
:IsCombine() may not be used for some schema

### ISSUE THREAD

**Issue by Lucasgood5** [n8zone/clothing-bags-base#1]
```
[ERROR] gamemodes/survived/plugins/rostd-bag-clothes/items/base/sh_clothingwithpockets.lua:37: attempt to call method 'IsCombine' (a nil value)
  1. OnCanRun - gamemodes/survived/plugins/rostd-bag-clothes/items/base/sh_clothingwithpockets.lua:37
   2. DoRightClick - gamemodes/helix/gamemode/core/derma/cl_inventory.lua:86
    3. unknown - gamemodes/helix/gamemode/core/derma/cl_inventory.lua:52 (x2)
```

Some schema (like mine) doesn't use Combine. You should only call the method if it exist and/or the `ITEM.civilProtectionItem` is `true`

Should be easy to fix.

**Comment by nathanmazzapica** [comment]
Hey, thanks for the report & pull request. Your fix will work for you but merging it would cause it to not work properly for servers running the HL2RP schema.

I'm working on an update that'll hopefully work for both HL2RP and non-HL2RP servers, again thank you for pointing this out.
